### PR TITLE
Allow parameters on variables

### PR DESCRIPTION
**Pull request by akurihara**
Gives users the ability to define parameters in the variable decorator that correspond to its function arguments.  
- When rules are processed by the `engine`, each condition that uses a parameterized variable must contain a dictionary whose values will be passed into that variable's function call.
- Added a validation method to `engine` that checks whether parameters given in conditions match those defined in variable and action decorators.

### CODE REVIEW

**Comment by cp2587** [comment]
Hi,
great work on the library. When do you plan to merge this branch ? I could really use have parameters in my rule variables.

**Comment by gregeinfrank** [comment]
@akurihara ping

**Comment by VRSandeep** [comment]
Any progress on merging this feature?

**Comment by gregeinfrank** [comment]
@akurihara

**Comment by dbaravalle** [comment]
@akurihara Any updates?

**Comment by gregeinfrank** [comment]
@akurihara sweet dude

**Comment by mrkcohen** [comment]
@akurihara damn i was really hyped on this

**Pull request closed without merging**
