### PR TITLE
Remove caching functionality to reduce the possibility of a memory leak

### PR DESCRIPTION
**Pull request by jwbixby**
There is no way to clear the memoize function's cache. This will result in a memory leak for users' scripts that are long lived.

I am proposing a major version bump(`1.0.0`) to remove this feature. A new caching feature could be added later in a way that would not hurt applications that are long lived.

### CODE REVIEW

**Comment by adamsc64** [comment]
Yeah, probably the right move for now.

**Comment by adamsc64** [comment]
Let's get @simon-weber's input on the deprecation strategy? But I'm :green_apple:

**Comment by adamsc64** [comment]
We should probably keep/update release notes. As long as the change is tracked somewhere and stated clearly with a warning, I'm :green_apple:

**Comment by simon-weber** [comment]
:+1: to major version bump

For release notes, I like to put them in a separate file then append the contents to the pypi description so they show up inline. eg: https://github.com/venmo/nose-detecthttp/blob/a4bd46fe99c9647d7a297d6aa2697a6a63e6146b/setup.py#L35 shows up as https://pypi.python.org/pypi/nose-detecthttp.

**Comment by adamsc64** [comment]
So one other option is to actually include the kwarg `cache_result` in the main decorators that are exported from `variables.py`. That way, developers could override it in their applications, but we can maintain backwards compatibility. It would also not require a major version bump.

**Comment by jwbixby** [comment]
It would require a major version bump if we defaulted to False, right? Otherwise everyone would need to default each individual decorator to false to remove it. Thoughts on that?

**Comment by simon-weber** [comment]
I think I'd prefer to see one of a) remove it entirely, or if we really want to keep it, b) add some form of invalidation, since:
* offering caching without any kind of invalidation feels like we're knowingly including a gotcha as a feature
* I don't think the backwards incompatible change is that bad: it seems unlikely there are users that both depend on the caching but also haven't turned it off due to memory concerns

**Comment by simon-weber** [comment]
:green_apple: nice

**Comment by adamsc64** [comment]
> It would require a major version bump if we defaulted to False, right?
Agreed - but if we kept default to True, we wouldn't need a major bump.

> offering caching without any kind of invalidation feels like we're knowingly including a gotcha
Also agreed - though we could open it as a known issue in the issue tracker and fix it sooner than later.

> it seems unlikely there are users that both depend on the caching
That I'm not sure about offhand. It's plausible that developers may depend on it in short scripts that terminate and clear the memory at the end, but otherwise have data-intensive queries. I'm struggling to figure out whether this "auto-caching" is actually a central feature of `business-rules`. I could see someone make the argument it is but I'm on the fence.

**Pull request merged**
